name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
      env:
        BITLY_OAUTH_TOKEN: ${{secrets.BITLY_OAUTH_TOKEN}}
      
  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/dobriychelpozitivniy/go-coding-challenge-jr:latest .
        docker run ghcr.io/dobriychelpozitivniy/go-coding-challenge-jr:latest
        docker push ghcr.io/dobriychelpozitivniy/go-coding-challenge-jr:latest
